<Project>
  <PropertyGroup>
    <ProGpuWpfSdkVersion>0.1.0-preview.29</ProGpuWpfSdkVersion>
    <ProGpuWpfPackageVersion>$(ProGpuWpfSdkVersion)</ProGpuWpfPackageVersion>
    <ProGpuWpfManagedPackageVersion>$(ProGpuWpfPackageVersion)</ProGpuWpfManagedPackageVersion>
    <ProGpuPackageVersion>0.1.0-preview.28</ProGpuPackageVersion>
    <ProGpuWpfLibreWinFormsPackageVersion>0.1.0-preview.29</ProGpuWpfLibreWinFormsPackageVersion>
    <ProGpuWpfSdkSampleTargetFramework Condition="'$(ProGpuWpfSdkSampleTargetFramework)' == ''">net10.0-windows</ProGpuWpfSdkSampleTargetFramework>
    <ProGpuWpfUsePortableWinFormsCompat>true</ProGpuWpfUsePortableWinFormsCompat>
    <ProGpuWpfUseLibreWinForms>true</ProGpuWpfUseLibreWinForms>
  </PropertyGroup>
</Project>
