<Project Sdk="LibreWPF.Sdk/0.1.0-preview.45">
  <PropertyGroup>
    <TargetFramework>$(ProGpuWpfSdkSampleTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>ICSharpCode.Core.Presentation</AssemblyName>
    <RootNamespace>ICSharpCode.Core.Presentation</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\ICSharpCode.SharpDevelop.snk</AssemblyOriginatorKeyFile>
    <DefineConstants>$(DefineConstants);LIBREWPF</DefineConstants>
    <NoWarn>$(NoWarn);1591;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj/**" />
    <EmbeddedResource Remove="obj/**" />
    <None Remove="obj/**" />
    <Page Remove="obj/**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
    <PackageReference Include="ProGPU.System.Drawing.Common" Version="$(ProGpuPackageVersion)" />
    <ProjectReference Include="..\Core\Project\ICSharpCode.Core.LibreWpf.csproj" />
  </ItemGroup>
</Project>
