<Project Sdk="LibreWPF.Sdk/0.1.0-preview.45">
  <PropertyGroup>
    <TargetFramework>$(ProGpuWpfSdkSampleTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>ICSharpCode.TreeView</AssemblyName>
    <RootNamespace>ICSharpCode.TreeView</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\Main\ICSharpCode.SharpDevelop.snk</AssemblyOriginatorKeyFile>
    <NoWarn>$(NoWarn);1591;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj/**" />
    <EmbeddedResource Remove="obj/**" />
    <None Remove="obj/**" />
    <Page Remove="obj/**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Main\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
    <ProjectReference Include="..\..\..\Main\Core\Project\ICSharpCode.Core.LibreWpf.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
